source 'https://rubygems.org'

gem 'rails'
gem 'rspec'
gem 'rspec-expectations'
gem 'byebug'
gem 'pry-rails'
gem 'dijkstra_trace'
gem 'ruby-prof'
gem 'parallel'
gem 'range_operators'
gem 'rb_heap'
gem 'rainbow'
gem 'z3' # sudo apt install libz3-dev
